spring:
  profiles: default
cfc: mycrcurldef11
errormsg: myErrorMessage-default

spring:
  profiles: default
cfc: mycrcurldef11
errormsg: myErrorMessage-default
 
---

spring:
  profiles: dev
cfc: mycrcur4444-changed6
errormsg: myErrorMessage-dev-edited-2


camel:
  log:
    msg1: Processing has been started
    msg2: Processing has been ended
 
---

spring:
  profiles: dev
cfc: mycrcur4444-changed6
errormsg: myErrorMessage-dev-edited-2


camel:
  log:
    msg1: Processing has been started
    msg2: Processing has been ended
